pipeline {
    agent any

    tools {
        maven 'Maven'    // Jenkins Maven installation name
        jdk 'jdk17'      // Jenkins JDK installation name
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Checking out code from GitHub..."
                git url: 'https://github.com/Alok123-tech/Test.git', branch: 'master'
            }
        }

        stage('Build') {
            steps {
                dir('Test/opencart_cucumber_framework') {
                    echo "Running Maven Build..."
                    sh 'mvn clean test'
                }
            }
        }

        stage('Archive Reports') {
            steps {
                dir('Test/opencart_cucumber_framework') {
                    junit '**/target/surefire-reports/*.xml'
                    publishHTML([allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'target/cucumber-html-reports',
                        reportFiles: 'overview-features.html',
                        reportName: 'Cucumber HTML Report'
                    ])
                }
            }
        }
    }
}
