pipeline {
    agent any
tools {
    maven 'Maven'
}
    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out code from GitHub...'
                git branch: 'master', url: 'https://github.com/Alok123-tech/Test.git'
                dir('opencart_cucumber_framework')
            }
        }

        stage('Build') {
            steps {
                dir('opencart_cucumber_framework')
                echo 'Building the project...'
                bat 'mvn -B clean compile'
            }
        }

        stage('Test') {
            steps {
                dir('opencart_cucumber_framework')
                echo 'Running tests...'
                bat 'mvn -B test'
            }
        }

        stage('Archive Reports') {
            steps {
                echo 'Archiving reports...'
                junit 'target/surefire-reports/*.xml'
                archiveArtifacts artifacts: 'reports/**, target/cucumber-reports/**, screenshot/**', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished'
        }
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed. Check console output.'
        }
    }
}
